# Site settings
title: KWmassage | Registered Massage Therapy in Kitchener/Waterloo
email: jeremy@kwmassage.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
destination: _site_production
baseurl: "" # the base hostname & protocol for your site
permalink: /:categories/:title/
paginate: 10
paginate_path: "/knowledge-centre/page/:num"
twitter_username: jekyllrb
github_username:  jekyll
exclude: [/__wp_backup__/, lib, robots.txt]
# Build settings
markdown: kramdown
