# Site settings
title: KWmassage | Registered Massage Therapy in Kitchener/Waterloo
email: jeremy@kwmassage.com
description: Specializing in Deep Tissue Massage and Trigger Point Release Therapy to bring you the relief you need from repetitive strain injuries and postural dysfunctions related to sports, the workplace, and family life.
url: "" # the subpath of your site, e.g. /blog/
destination: _site_production
baseurl: "" # the base hostname & protocol for your site
permalink: /:categories/:title/
paginate: 10
paginate_path: "/knowledge-centre/page/:num"
twitter_username: jekyllrb
github_username:  jekyll
exclude: [/__wp_backup__/, lib, robots.txt, canvas, gulpfile.js, node_modules]
# Build settings
markdown: kramdown
gems:
    - jekyll-paginate

###
#  To publish production version
# jekyll serve --config _config_production.yml
###